server:
  port: 8098
  servlet.contextPath: /api/dev-ops/jira

spring:
  profiles.active: dev  # 生产环境和测试环境选择 dev或pro或test

  application:
    name: JIRA_SERVICE

#forest:
#  max-connections: 1000        # 连接池最大连接数
#  connect-timeout: 3000        # 连接超时时间，单位为毫秒
#  read-timeout: 3000           # 数据读取超时时间，单位为毫秒
