jira:
  host: http://localhost:2990/jira
  username: admin
  password: admin
  pointName: Story Point
  sprintName: Sprint

  apiProject: /rest/api/latest/project
  apiField: /rest/api/latest/field
  # /rest/agile的maxResults不能设置为-1，小于1时，会自动变为1
  apiBoards: /rest/agile/latest/board?projectKeyOrId=%s&maxResults=1000
  apiSprint: /rest/agile/latest/board/%s/sprint?state=future,active&maxResults=1000
  jql: /rest/api/latest/search
  jqlByProject: project in (%s) AND issuetype = 子任务 AND "%s" > 0 AND Sprint not in closedSprints()
